### ISSUE TITLE
issues with server-address and rw protection(?)

### ISSUE THREAD

**Issue by cicci44** [go-vikunja/app#53]
using docker, when connection using laptop to frontend, everything works fine.. heres the config i used.. 
```
version: '3'

services:
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: x
      MYSQL_USER: z
      MYSQL_PASSWORD: y
      MYSQL_DATABASE: y
    volumes:
      - ./srv/dev-disk-byx/appdata/vikunja/db:/var/lib/mysql
    restart: unless-stopped
  api:
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: x
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: y
      VIKUNJA_DATABASE_DATABASE: y
      VIKUNJA_SERVICE_JWTSECRET: x
      VIKUNJA_SERVICE_FRONTENDURL: http://192.168.1.100/
    ports:
      - 3456:3456
    volumes:
      - ./srv/dev-disk-byx/appdata/vikunja/files:/app/vikunja/files
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    image: vikunja/frontend
    ports:
      - 8013:80
    environment:
      VIKUNJA_API_URL: http://192.168.1.100:3456/api/v1
    restart: unless-stopped
```

in android app..first time login.. with username/password at server address
192.168.1.100
gives error "no host specified" and the url looks like the http(s) is missing, changing it to
http://192.168.1.100
gives error "error on request: failed host", i guess i need to specify port 8013 but it wont work either.. maybe port 3456?
http://192.168.1.100:3456
gives "message": "not found", perhaps /api/v1 ? 
http://192.168.1.100:3456/api/v1 
OK, now it works! .. suggestion is to add that as example like the try.vikunja.io address.

- adding a new task in android-application gives me 404 (message: not found Url: http://192.168.1.100:3456/api/v1/projects/1/tasks
- complete task thats already setup via laptop works fine in android-application.
- edit task thats already setup via laptop works fine in android-application
- remove task thats already setup via laptop works fine in android-application...

uhm, perhaps read/write error?
